require('should');
require('./test.js');
require('./av.js');
require('./file.js');
require('./error.js');
// require('./captcha.js');
require('./object.js');
require('./user.js');
require('./query.js');
require('./geopoints.js');
require('./acl.js');
require('./role.js');
require('./status.js');
require('./sms.js');
require('./search.js');
require('./hooks.js');
