version: 2

group_defaults:
  reset_on_push:
    enabled: true
  github_reviews:
    enabled: true
  approve_by_comment:
    enabled: true
    approve_regex: '^(Reviewed|Approved|LGTM)'
    reject_regex: '^Rejected'

groups:
  reviewers:
    required: 1
    users:
      - jwfing
      - leeyeh
      - aisk
